name: 'Hello Wolrd JS Action'
description : 'Greet someone and record the time'
inputs:
  who-togreet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'